config/routes.rb
Rails.application.routes.draw do
  resources :transactions, only: [:new, :create]

  resources :reservations, except: [:update, :edit]
  resources :profiles, except: [:index, :destroy]

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  root 'welcome#index'
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  resources :users, only: [:show, :edit, :update, :destroy] 
  resources :listings

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  validates_uniqueness_of :user_id
  mount_uploader :picture, ImageUploader
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  def create

    @profile = Profile.new(profile_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /profiles/1
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /profiles/1
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:name, :location, :contact, :picture, :user_id)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div><br>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :contact %><br>
    <%= f.text_field :contact %>
  </div><br>
  <div class="actions">
    <%= f.submit class:"btn btn-success" %>
  </div><br>
<% end %>

app/views/profiles/edit.html.erb
<div class="container">
  <br>
  <%= render 'form' %>

  <%= link_to 'Back', root_path, class:"btn btn-info" %>
</div>

app/views/profiles/new.html.erb
<div class="container">
  <br>
  <%= render 'form' %>

  <%= link_to 'Back', root_path, class:"btn btn-info" %>
</div>

app/views/profiles/show.html.erb
<div class="container">
  <br><br>
  <p>
    <%= image_tag @profile.picture_url(:profile).to_s, class:"img-circle" %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= @profile.name %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= @profile.location %>
  </p>

  <p>
    <strong>Contact:</strong>
    <%= @profile.contact %>
  </p>

  <p>
    <strong>Email</strong>
    <%= @profile.user.email %>
  </p>

  <p><%= link_to "Listings by #{@profile.name}", listings_path(user_id: @profile.user.id)%><br></p>
  <% if @profile.user == current_user %>
    <%= link_to 'Edit', edit_profile_path(@profile), class:"btn btn-warning" %>
  <% end %>
</div>