config/routes.rb
Rails.application.routes.draw do
  resources :transactions, only: [:new, :create]

  resources :reservations, except: [:update, :edit]
  resources :profiles, except: [:index, :destroy]

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  root 'welcome#index'
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  resources :users, only: [:show, :edit, :update, :destroy] 
  resources :listings

end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :user
  has_many :reservations, :dependent => :destroy
  mount_uploaders :pictures, PictureUploader
  validates_presence_of :price
  searchkick
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  before_action :require_login, only: [:edit, :update, :destroy, :create, :new]

  def create
    @listing = Listing.new(listing_params)
    if @listing.save
      redirect_to @listing
    else
      render :new
    end
  end

  def new
    @listing = Listing.new
  end

  def show
    @listing = Listing.find(params[:id])
  end

  def index
    if params[:query].present?
      @listings = Listing.search(params[:query])
    elsif params[:user_id].present?
      @listings = Listing.where(user_id: params[:user_id])
      if User.find(params[:user_id]) == current_user
        @can_add = true
      end
    else
      @listings = Listing.all
      @can_add = true
    end
  end

  def update
    @listing = Listing.find(params[:id])
    byebug
    @listing.update(listing_params)
    if @listing.save
      redirect_to @listing
    else
      render :edit
    end
  end

  def edit
    @listing = Listing.find(params[:id])
    redirect_to @listing if current_user != @listing.user
  end

  def destroy
    @listing = Listing.find(params[:id])
    redirect to listings_path if current_user != @listing.user
    @listing.destroy
    redirect_to listings_path
  end
end

private

def listing_params
  params[:listing][:user_id] = current_user.id
  params.require(:listing).permit(:name, :home_type, :room_type, :accommodates, :address, :city, :price, :user_id, {pictures: []})
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for(@listing) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pictures %><br>
    <%= f.file_field :pictures, multiple: true %>
  </div><br>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :home_type %><br>
    <%= f.text_field :home_type %>
  </div>
  <div class="field">
    <%= f.label :room_type %><br>
    <%= f.text_field :room_type %>
  </div>
  <div class="field">
    <%= f.label :accommodates %><br>
    <%= f.number_field :accommodates %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price, step: 0.01 %>
  </div><br>
  <div class="actions">
    <%= f.submit class:"btn btn-success" %>
  </div><br>
<% end %>

app/views/listings/edit.html.erb
<div class="container">
  <br>
  <%= render 'form' %>

  <%= link_to 'Back', listing_path, class:"btn btn-info" %>
</div>

app/views/listings/index.html.erb
<div class="container">
  <% if @listings.length == 0 %>
    <br><h3>No listings found</h3><br>
  <% else %>
    <br><br>
    <% @listings.each do |listing| %>
      <div class="row"><!-- Full Row -->      
        <div class="col-lg-3"><!-- Picture Box-->
          <%= image_tag listing.pictures.first.url(:thumb).to_s %>
        </div><!-- End Picture Box -->
        <div class="col-lg-6"><!-- Info Box -->
          <h3><%= link_to "#{listing.name}", listing %></h3>
          <p>Home type: <%= listing.home_type %></p>
          <p>Room type: <%= listing.room_type %></p>
          <p>Accomodates: <%= listing.accommodates %></p>
          <p>Address: <%= listing.address %></p>
          <p>City: <%= listing.city %></p>
        </div><!-- End Info Box -->
        <div class="col-lg-3"><!-- User Box -->
          <p>Posted by:</p>
          <p><%= image_tag listing.user.profile.picture_url(:thumb).to_s, class:"img-circle" %> <%= link_to "#{listing.user.profile.name}", profile_path(listing.user.profile) %></p>
          <% if listing.user == current_user %>
            <p>
              <%= link_to 'Edit', edit_listing_path(listing), class:"btn btn-warning" %>
              <%= link_to 'Delete', listing, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
            </p>
          <% end %>          
        </div><!-- End User Box -->
        <hr>
      </div><!-- End Full Row -->
      <hr>
    <% end %>
  <% end %>
  <% if @can_add %>
    <%= link_to 'Create A New Listing', new_listing_path, class:"btn btn-success" %>
  <% end %>
</div>

app/views/listings/new.html.erb
<div class="container">
  <br>
  <%= render 'form' %>

  <%= link_to 'Back', listings_path, class:"btn btn-info" %>
</div>

app/views/listings/show.html.erb
<div class="container">
  <br>
  <div class="row">
    <div class="col-lg-10"><h2><%= @listing.name %></h2></div>
    <div class="col-lg-2 text-right">
      <p>by: <%= link_to "#{@listing.user.profile.name}", profile_path(@listing.user.profile) %> <%= image_tag @listing.user.profile.picture_url(:thumb).to_s, class:"img-circle" %></p>
    </div>
  </div>
  <hr>
  <p>
    <strong>Pictures:</strong><br>
    <% if @listing.pictures %>
      <div class="carousel slide" id="screenshot-carousel" data-rise="carousel"><!-- Variable Carousel -->
        <ol class="carousel-indicators">
          <% @listing.pictures.each_with_index do |picture, index| %>
            <% if index == 0 %>
              <li data-target="screenshot-carousel" data-slide-to="#{index}" class="active"></li>            
            <% else %>
              <li data-target="screenshot-carousel" data-slide-to="#{index}"></li>
            <% end %>
          <% end %>
        </ol>
        <div class="carousel-inner">
          <% @listing.pictures.each_with_index do |picture, index| %>
            <% if index == 0 %>
              <div class="item active">
                <%= image_tag picture.url(:full).to_s %>
              </div>
            <% else %>
              <div class="item">
                <%= image_tag picture.url(:full).to_s %>
              </div>
            <% end %>            
          <% end %>
        </div>
        <a href="#screenshot-carousel" class="left carousel-control" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a href="#screenshot-carousel" class="right carousel-control" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
      </div><!-- End Variable Carousel -->
    <% else %>
      <p>No picture for this listing yet</p>
    <% end %>
  </p>

  <p>
    <div class=row>
      <div class="col-sm-2"><strong>Price per night:</strong></div>
      <div class="col-sm-10"><%= @listing.price %></div>
    </div>
  </p>

  <p>
    <div class=row>
      <div class="col-sm-2"><strong>Home type:</strong></div>
      <div class="col-sm-10"><%= @listing.home_type %></div>
    </div>
  </p>

  <p>
    <div class="row">
      <div class="col-sm-2"><strong>Room type:</strong></div>
      <div class="col-sm-10"><%= @listing.room_type %></div>
    </div>
  </p>

  <p>
    <div class="row">
      <div class="col-sm-2"><strong>Accommodates:</strong></div>
      <div class="col-sm-10"><%= @listing.accommodates %></div>
    </div>
  </p>

  <p>
    <div class="row">
      <div class="col-sm-2"><strong>Address:</strong></div>
      <div class="col-sm-10"><%= @listing.address %></div>
    </div>
  </p>

  <p>
    <div class="row">
      <div class="col-sm-2"><strong>City:</strong></div>
      <div class="col-sm-10"><%= @listing.city %></div>
    </div>
  </p>


  <p>
    <div class="row">
      <div class="col-sm-2"><strong>Current Reservations:</strong></div>
      <div class="col-sm-10">
        <% if @listing.reservations.count == 0 %>
          <p>This listing currently has no reservations.</p>
        <% else %>
          <table class="table table-striped">
            <tr>
              <th>Guest</th>
              <th>From</th>
              <th>Until</th>
              <th colspan="1"></th>
            </tr>
            <% @listing.reservations.each do |reservation| %>
              <tr>
                <td><%= reservation.user.profile.name %></td>
                <td><%= reservation.from %></td>
                <td><%= reservation.until %></td>
                <td>
                  <% if reservation.paid? %>
                    <p class="btn btn-info">Paid</p>
                  <% else %>
                    <p class="btn btn-warning">Pending</p>
                    <% if current_user == reservation.user %>
                      <%= link_to 'Pay Now', new_transaction_path(reservation_id: reservation), class:"btn btn-info" %>
                    <% end %>
                  <% end %>
                  <% if current_user == reservation.user %>
                    <%= link_to 'Delete', reservation, class:"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </table>
        <% end %>
        <div>
          <% if @listing.user != current_user %>
            <%= link_to 'Make A Reservation', new_reservation_path(listing_id: @listing), class:"btn btn-success" %>
          <% end %>
        </div>
      </div>
    </div>
  </p>
  <%= link_to 'Back', listings_path, class:"btn btn-info" %>
  <% if current_user == @listing.user %>
  <%= link_to 'Edit', edit_listing_path(@listing), class:"btn btn-warning" %>
  <% end %>
</div>