config/routes.rb
Rails.application.routes.draw do
  resources :transactions, only: [:new, :create]

  resources :reservations, except: [:update, :edit]
  resources :profiles, except: [:index, :destroy]

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  root 'welcome#index'
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  resources :users, only: [:show, :edit, :update, :destroy] 
  resources :listings

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def new
    @reservation = Reservation.find(params[:reservation_id])
    gon.client_token = generate_client_token
  end

  def create
    @reservation = Reservation.find(params[:reservation_id])
    @result = Braintree::Transaction.sale(
              amount: @reservation.total_price,
              payment_method_nonce: params[:payment_method_nonce])
    if @result.success?
      @reservation.paid!
      Transaction.create(reservation_id: @reservation.id, braintree: @result.transaction.id)
      redirect_to @reservation.listing
    else
      flash[:alert] = "Something went wrong while processing your transaction. Please try again!"
      gon.client_token = generate_client_token
      render :new
    end
  end

  private
  def generate_client_token
    Braintree::ClientToken.generate
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/new.html.erb
<div class="container">
<br>
<h2>Payment in progress for the following reservation:</h2>
<hr>

<div class="row"><!-- Details Row -->
  <div class="col-lg-3">
    <%= image_tag @reservation.listing.pictures.first.url(:thumb).to_s %>
  </div>
  <div class="col-lg-9">
  <h3><%= @reservation.listing.name %></h3>
  <p><%= @reservation.listing.city %></p>
  <p>Price per night: <%= @reservation.listing.price %></p>
  <p>Check-in date: <%= @reservation.from %></p>
  <p>Check-out date: <%= @reservation.until %></p>
  <p>Total price: <%= @reservation.total_price %></p>
  </div>
</div><!-- End Details Row -->
<hr>
  
<div class="container">
  <div class="form-container radius-box glassy-bg small-10 small-centered medium-8 large-6 columns">
    <%= form_tag transactions_path do%>
      <p><strong>Please enter your payment details:</strong></p>
      <div id="dropin"></div>
      <%= hidden_field_tag(:reservation_id, @reservation.id) %>
      <%= submit_tag "Pay #{@reservation.total_price}$", class: "button mt1" %>
    <%end%>
  </div>
</div>