config/routes.rb
Rails.application.routes.draw do
  resources :transactions, only: [:new, :create]

  resources :reservations, except: [:update, :edit]
  resources :profiles, except: [:index, :destroy]

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  root 'welcome#index'
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  resources :users, only: [:show, :edit, :update, :destroy] 
  resources :listings

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base

 belongs_to :user

  def self.create_with_omniauth(auth_hash)
    create! do |auth|
      auth.provider = auth_hash["provider"]
      auth.uid = auth_hash["uid"]
      auth.token = auth_hash["credentials"]["token"]
    end
  end

  def update_token(auth_hash)
    self.token = auth_hash["credentials"]["token"]
    self.save
  end

end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :user
  has_many :reservations, :dependent => :destroy
  mount_uploaders :pictures, PictureUploader
  validates_presence_of :price
  searchkick
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  validates_uniqueness_of :user_id
  mount_uploader :picture, ImageUploader
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  belongs_to :listing
  has_many :transactions

  def total_price
    total_price = self.listing.price * (self.until - self.from)
    return total_price.to_f
  end

  def paid!
    self.paid = true
    self.save!
  end

  def paid?
    return true if self.paid
  end
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :reservation

end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  has_many :authentications, :dependent => :destroy
  has_many :listings
  has_one :profile
  has_many :reservations

  def self.create_with_auth_and_hash(authentication,auth_hash)
    create! do |u|
      u.email = auth_hash["extra"]["raw_info"]["email"]
      u.encrypted_password = [*('A'..'Z')].sample(8).join
      u.authentications<<(authentication)
    end
  end

  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end

  def password_optional?
    true
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  before_action :require_login, only: [:edit, :update, :destroy, :create, :new]

  def create
    @listing = Listing.new(listing_params)
    if @listing.save
      redirect_to @listing
    else
      render :new
    end
  end

  def new
    @listing = Listing.new
  end

  def show
    @listing = Listing.find(params[:id])
  end

  def index
    if params[:query].present?
      @listings = Listing.search(params[:query])
    elsif params[:user_id].present?
      @listings = Listing.where(user_id: params[:user_id])
      if User.find(params[:user_id]) == current_user
        @can_add = true
      end
    else
      @listings = Listing.all
      @can_add = true
    end
  end

  def update
    @listing = Listing.find(params[:id])
    byebug
    @listing.update(listing_params)
    if @listing.save
      redirect_to @listing
    else
      render :edit
    end
  end

  def edit
    @listing = Listing.find(params[:id])
    redirect_to @listing if current_user != @listing.user
  end

  def destroy
    @listing = Listing.find(params[:id])
    redirect to listings_path if current_user != @listing.user
    @listing.destroy
    redirect_to listings_path
  end
end

private

def listing_params
  params[:listing][:user_id] = current_user.id
  params.require(:listing).permit(:name, :home_type, :room_type, :accommodates, :address, :city, :price, :user_id, {pictures: []})
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  def create

    @profile = Profile.new(profile_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /profiles/1
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /profiles/1
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:name, :location, :contact, :picture, :user_id)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController

  def create_from_omniauth
    auth_hash = request.env["omniauth.auth"]

    authentication = Authentication.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"]) || Authentication.create_with_omniauth(auth_hash)
    if authentication.user
      user = authentication.user 
      authentication.update_token(auth_hash)
      @next = root_url
      @notice = "Signed in!"
    else
      user = User.create_with_auth_and_hash(authentication,auth_hash)
      @next = root_url   
      @notice = "User created - confirm or edit details..."
    end
    sign_in(user)
    redirect_to @next, :notice => @notice
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <%= include_gon %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tag %>
    <meta name=“viewport” content=“width=device width, initial-scale=1.0”>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    <title>Welcome to RazBnB</title>
  </head>

  <style>
    body{
      padding-top: 40px;
    }
    .jumbotron {
      background-image: url(https://s3-ap-southeast-1.amazonaws.com/razbnb/uploads/layout/pictures/jumbotron.jpg);
      background-position: 15% 35%;
      background-size: cover;
      background-repeat: no-repeat;
      color: white;
    }  
  </style>

  <body>

    <!-- Navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top" id="my-navbar">
      <div class=container>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="/" class="navbar-brand"><img style="margin-top:-0.5em;" src="https://s3-ap-southeast-1.amazonaws.com/razbnb/uploads/layout/pictures/RazBnB.png"></a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse">
          <ul class="nav navbar-nav">
            <% if signed_in? && current_user.profile != nil %>
              <li><%= link_to "Profile", profile_path(current_user.profile) %></li>
              <li><%= link_to "My Listings", listings_path(user_id: current_user.id) %></li>
            <% elsif signed_in? && current_user.profile == nil %>
              <li><%= link_to "Profile", new_profile_path %></li>
              <li><%= link_to "My Listings", listings_path(user_id: current_user.id) %></li>
            <% end %>
            <li><a href="/listings">All Listings</a></li>
          </ul>
          <% if signed_in? %>
            <%= link_to "Sign out", sign_out_path, method: :delete, class:"btn btn-warning navbar-btn navbar-right" %>
          <% else %>
            <%= link_to "Sign in", sign_in_path, class:"btn btn-warning navbar-btn navbar-right" %>
          <% end %>
          <form action="/listings" method="get" class="navbar-form navbar-right" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search RazBnB" name="query">
            </div>
            <button type="submit" class="btn btn-default">Search</button>
          </form>
        </div>
      </div>
    </nav><!-- End Navbar -->

    <%= yield %>
    <footer>
      <div class="container text-center">
        <hr>
        <p>&copy; RazBnB, Inc.</p>
      </div>      
    </footer>

    <script src="https://js.braintreegateway.com/v2/braintree.js"></script>
    <script src="http://code.jquery.com/jquery-2.1.1.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  </body>

</html>